modLoader="javafml"
loaderVersion="[47,)"
license="MCreator"

[[mods]]
modId="dani_modja"
version="1.0.0"
displayName="Dani modja"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="RocKoala3"
description="It's a small mod XD"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.dani_modja]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration